src/senshu/scoreserver/urls.py
from django.conf.urls import url, include, handler403, handler404
from django.contrib import admin
import django.contrib.auth.views as auth_views
from . import views
from .views import QuestionListView
from .views import QuestionDetailView
from .views import ScoreBoardView, WebView, NetworkView, CryptoView, ForensicsView, BinaryView, MiscView
from .views import RegisterView

handler404 = 'scoreserver.views.not_found'
handler403 = 'scoreserver.views.forbidden'

app_name = 'scoreserver'
urlpatterns = [
    #index page
    url(r'^index/$', views.index, name="index"),
    #login and logout
    url(r'^login', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view,  name="logout"),
    #scoreboard
    url(r'^scoreboard/$', ScoreBoardView.as_view(), name="scoreboard"),
    #User create, update, delete
    url(r'^register/$', RegisterView.as_view(), name="register"),
    #flag submit
    url(r'^submit/(?P<question_id>\d+)/$', views.flag_submit_view, name="submit"),
    #question list, detail, each category
    url(r'^questions/$', QuestionListView.as_view(), name="questions"),
    url(r'^question_detail/(?P<pk>\d+)/$', QuestionDetailView.as_view(), name="question_detail"),
    url(r'^web/$', WebView.as_view(), name="web"),
    url(r'^network/$', NetworkView.as_view(), name="network"),
    url(r'^crypt/$', CryptoView.as_view(), name="crypt"),
    url(r'^forensics/$', ForensicsView.as_view(), name="forensics"),
    url(r'^reversing/$', BinaryView.as_view(), name="reversing"),
    url(r'^misc/$', MiscView.as_view(), name="misc")
]

src/senshu/senshu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^scoreserver/', include('scoreserver.urls')),
    url(r'^admin/', admin.site.urls),
]

src/senshu/scoreserver/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class Category(models.Model):
    """ 問題のカテゴリ """
    name = models.CharField(default='', max_length=50, unique=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    """ 問題 """
    category = models.ForeignKey(Category, verbose_name="カテゴリ")
    title = models.CharField(max_length=50)
    description = models.TextField(default='')
    solved = models.IntegerField("解いた人の数", blank=True, null=True)
    url = models.CharField(max_length=50, null=True)

class Flag(models.Model):
    """ 問題の答え(フラグ) """
    question = models.ForeignKey(Question, verbose_name="問題", unique=True)
    flag = models.CharField(max_length=50, unique=True)
    point = models.IntegerField("得点")

class Hint(models.Model):
    """ 問題のヒント """
    question = models.ForeignKey(Question, verbose_name="問題")
    description = models.TextField(default='')

    def __str__(self):
        return self.description

class UserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError("Users must have username!!")
        if len(User.objects.filter(username=username)) > 0:
            raise ValueError("This user had already registered!!")

        user = self.model(username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        u = self.create_user(username, password=password)
        u.is_superuser = True
        u.is_staff = True
        u.save(using=self._db)
        return(u)

class User(AbstractBaseUser):
    """ CTFのプレイヤー """
    class Meta:
        ordering = ("-points",)
        db_table = 'scoreserver_user'

    username = models.CharField(default='', max_length=50, unique=False)
    #password = models.CharField(max_length=128, verbose_name="パスワードハッシュ")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    points = models.IntegerField(default=0)

    USERNAME_FIELD = 'username'
    #PASSWORD_FIELD = 'password'

    objects = UserManager()

    def __unicode__(self):
        return self.username

    def update_points(self):
        """pointsの更新"""
        print("Calculating points....")
        points = 0
        my_attack_point_history = AttackPointHistory.objects.filter(user=self)
        for point in map(lambda mah: mah.point, my_attack_point_history):
            points += point
        self.points = points

    def set_password(self, raw_password):
        """ パスワード設定 """
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        print("Authenticating...")
        """ 生パスワードのチェック """
        def setter(raw_password):
            """ パスワード更新 """
            self.set_password(raw_password)
            self.save(update_fields=["password"])
        return check_password(raw_password, self.password, setter)

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def get_short_name(self):
        return self.username

class AttackPointHistory(models.Model):
    """ 成功した攻撃の履歴 """
    user = models.ForeignKey(User, verbose_name="ユーザ")
    question = models.ForeignKey(Question, verbose_name="問題")
    point = models.IntegerField("得点")

    def __str__(self):
        return """
        {user}が正解したディ! :100:
        カテゴリ:     {question_category}
        問題:         {question_title}
        獲得ポイント:  {point} pt
        獲得後ポイント: {acquired_point} pt
        """.format(
                user=self.user.username,
                question_category=self.question.category.name,
                question_title=self.question.title,
                point=self.point,
                acquired_point=self.user.points
        )

class AnswerHistory(models.Model):
    """ 回答履歴（成功しているかに関わらず） """
    user = models.ForeignKey(User, verbose_name="回答者")
    question = models.ForeignKey(Question, verbose_name="問題")
    submit_flag = models.CharField(max_length=50, verbose_name="提出フラグ")
    #正解フラグもあったほうが良い？

    def __str__(self):
        return """
        {user}が間違ったフラグを提出したディ... :broken_heart:
        カテゴリ:   {question_category}
        問題:      {question_title}
        提出フラグ: {submit_flag}
        """.format(
            user=self.user.username,
            question_category=self.question.category.name,
            question_title=self.question.title,
            submit_flag=self.submit_flag
        )

src/senshu/scoreserver/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()

src/senshu/scoreserver/views.py
#-*- coding: utf-8 -*-

import json
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect, render_to_response
from django.views import generic
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.context import RequestContext
from django.template.loader import get_template
from .models import Question, Flag, AnswerHistory, AttackPointHistory, Hint
from django.contrib.auth import get_user_model
User = get_user_model()
from scoreserver.helpers import FlagSubmit, get_ranking_info, is_already_attacked, get_user_solved_questions, is_already_exist_user
from django.db import connection

# Create your views here.

#競技中に行われ無いような操作は<Option>
#Todos
#問題詳細画面、ちょっと上に寄りすぎ。見辛い
#ログアウトボタン欲しいので、サイドバーに追加するなりして欲しい
#サイドバーだけでなくトップバーを用意し、そこにログアウトボタンとか
#ログイン時、Remember me 処理
#flag投稿時のモーダル

# --- index page ---

def index(request):
    context = {}
    return render(request, 'scoreserver/index.html', context)

# --- login and logout

def login_view(request):
    template_name = reverse('scoreserver:questions')
    #nextが指定されていれば、そこにリダイレクトさせるようにする
    if 'next' in request.GET.keys():
        template_name = request.GET['next']
    context=RequestContext(request, {})
    user = None
    if request.POST: #ログインPOSTしてきているのであれば
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)

        if user is not None: #認証成功かつ
            if user.is_active: #Userが有効
                login(request, user) #ログイン
                if "rememberMe" in request.POST:
                    request.session.set_expiry(2*7*24*60*60) # 2weeks (django default value)
                else:
                    request.session.set_expiry(24*60*60) #1 day
                return HttpResponseRedirect(template_name) #リダイレクト
            else:
                context['is_inactive'] = True #Userが無効である旨
        else:
            context['login_failed'] = True #ログイン失敗である旨

    context['title'] = "login"
    context['request'] = request
    context['checked_user'] = user #確認済みのユーザ(Template側で認証済みユーザオブジェクトと分けるため)
    return render(request, 'scoreserver/login.html', context)

@login_required(login_url="/scoreserver/login") #ログイン済みでなければ、ログアウトする意味がわからない
def logout_view(request):
    template_name = "scoreserver/logout.html"
    logout(request) #ログアウト
    return render(request, template_name, {"logout": True})

# --- Flag submit ---

@login_required(login_url="/scoreserver/login") #ログインしないとフラグは提出できない
def flag_submit_view(request, question_id):
    context = {}
    context['title'] = "Question Detail"
    flag = request.POST['flag'] #提出されてきたフラグを取得
    answer = Flag.objects.get(question=question_id).flag #正解のフラグをDBから取得
    fs = FlagSubmit(request.user, question_id, flag) #フラグ提出管理インスタンス生成
    #まだ正解しておらず、フラグが正しいのであれば攻撃成功とみなす
    if not is_already_attacked(request.user, question_id):
        if flag == answer: #正解した
            fs.success() #正解時の処理を行う
            message = "Congraturations! flag is correct!"
            status = 1
        else:
            fs.fail() #不正解時の処理を行う
            message = "Oh... flag is incorrect... please try again!"
            status = 2
    else:
        message = "You're already attacked this question." #既にこの問題に対し、攻撃が成功済みである
        status = 3
    response = json.dumps({
        "status": status,
        "message": message,
    })
    return HttpResponse(response, content_type='application/json')

# --- User Views (Register, Delete) ---

class RegisterView(generic.edit.CreateView):
    template_name = "scoreserver/register.html"
    model = User
    fields = ['username', 'password']
    success_url = reverse_lazy("scoreserver:index")

    def form_valid(self, form):
        username = self.request.POST["username"]
        password = self.request.POST["password"]
        if is_already_exist_user(username):
            messages.warning(self.request, "This user had already registered!!")
            return redirect(reverse_lazy("scoreserver:register"))
        result = super(RegisterView, self).form_valid(form)
        if result: #フォームのバリデーションに引っかからなかったら、一緒にログイン処理もこちら側で行ってしまう
            #super.form_validでは生パスワードを設定してしまうため、こちら側で行う
            registered_user = User.objects.get(username=username)
            registered_user.set_password(password)
            registered_user.save()
            messages.success(self.request, "Saved {}!".format(username))
            if self.request.user.is_authenticated(): #ログイン済みであれば
                logout(self.request) #一旦ログアウト
            authenticated_user = authenticate(username=username, password=password)
            if authenticated_user is not None:
                login(self.request, authenticated_user)
            else:
                messages.warning(self.request, "Please login")
            print("Register Executed Queries {}".format(connection.queries))
        else: #引っかかった
            messages.warning(self.request, "Something went wrong... Please contact a system administrator.")
        return result

    def form_invalid(self, form):
        messages.warning(self.request, "Can't saved...")
        return super(RegisterView, self).form_invalid(form)



# --- Question Views ---

class QuestionListView(LoginRequiredMixin, generic.ListView):
    """
    Question一覧を表示するビュー
    """
    login_url = '/scoreserver/login'
    #redirect_field_name = 'scoreserver/index'
    template_name = 'scoreserver/questions.html'
    context_object_name = 'questions'

    def get_context_data(self, **kwargs):
        context = super(QuestionListView, self).get_context_data(**kwargs)
        #for sidebar
        request = context['view'].request
        context['all_user_num'], context['login_user_rank'] = get_ranking_info(request)
        context['title'] = "questions"

        #for question, questions
        context['solved_questions'] = get_user_solved_questions(self.request.user)
        questions = Question.objects.all() #配列
        #DoesNotExist例外ハンドラを書くべき
        points = [flag.point for flag in [Flag.objects.get(question=question) for question in questions]]
        context['zipped_questions_points'] = zip(questions, points)
        return context

    def get_queryset(self):
        return Question.objects.all

class ScoreBoardView(LoginRequiredMixin, generic.TemplateView):
    """
    スコアボードを表示するビュー
    """
    template_name = "scoreserver/scoreboard.html"

    def get_context_data(self, **kwargs):
        context = super(ScoreBoardView, self).get_context_data(**kwargs)
        #for sidebar
        request = context['view'].request
        context['all_user_num'], context['login_user_rank'] = get_ranking_info(request)

        #for scoreboard
        context["title"] = "scoreboard"
        context["users"] = User.objects.filter(is_superuser=False, is_staff=False)#.order_by('-points')
        return context

class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    """
    Questionの詳細画面を表示するビュー
    """
    template_name = "scoreserver/question_detail.html"
    queryset = Question.objects.all()
    context_object_name = "question"

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        #for sidebar
        request = context['view'].request
        context['all_user_num'], context['login_user_rank'] = get_ranking_info(request)

        #for question_detail
        context['title'] = "Question Detail"
        return context

#基底クラス
class CategoryTemplateView(LoginRequiredMixin, generic.TemplateView):
    """
    カテゴリ(Web, Network, Crypto, Forensics, Binary, Misc)の基底クラス
    """
    model = Question
    def get_context_data(self, **kwargs):
        context = super(CategoryTemplateView, self).get_context_data(**kwargs)
        #for sidebar
        request = context['view'].request
        context['all_user_num'], context['login_user_rank'] = get_ranking_info(request)
        context['solved_questions'] = get_user_solved_questions(self.request.user)
        return context

    def get_zipped_context_data(self, category):
        """
        categoryのquestionsと、それに対応付いたpointsをzipで固めて返す
        :param category: カテゴリの文字列("Web", "Network", ...)
        :return: #categoryの問題(questions)とその問題の得点(points)をzipで固めて返す
        """
        questions = Question.objects.filter(category__name=category) #配列
        #DoesNotExist例外ハンドラを書くべき
        #気のせいかもしれないが、questionsと順番があっていないとダメなので、要チェック
        points = [flag.point for flag in [Flag.objects.get(question=question) for question in questions]]
        return(zip(questions, points))


class WebView(CategoryTemplateView):
    template_name = "scoreserver/question.html"
    def get_context_data(self, **kwargs):
        context = super(WebView, self).get_context_data(**kwargs)
        #for question
        context["title"] = "Web"
        context['zipped_questions_points'] = self.get_zipped_context_data("Web")
        return context

class NetworkView(CategoryTemplateView):
    template_name = "scoreserver/question.html"
    def get_context_data(self, **kwargs):
        context = super(NetworkView, self).get_context_data(**kwargs)
        #for question
        context["title"] = "Network"
        context['zipped_questions_points'] = self.get_zipped_context_data("Network")
        return context

class CryptoView(CategoryTemplateView):
    template_name = "scoreserver/question.html"
    def get_context_data(self, **kwargs):
        context = super(CryptoView, self).get_context_data(**kwargs)
        #for question
        context["title"] = "Crypto"
        context['zipped_questions_points'] = self.get_zipped_context_data("Crypto")
        return context

src/senshu/scoreserver/templates/scoreserver/bootcard.html
{% load staticfiles %}
{% load sass_tags %}
<head>
    <link rel="stylesheet" href="{% sass_src 'css/bootcards-desktop.scss' %}">
    <script src="{% static 'js/bootcards.js' %}"></script>
</head>

src/senshu/scoreserver/templates/scoreserver/bootstrap.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

src/senshu/scoreserver/templates/scoreserver/head.html
{% load staticfiles %}
<head>
<meta charset="UTF-8">
<title>{{title}}</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/snipet.css' %}">
</head>
{% include "scoreserver/bootstrap.html" %}

src/senshu/scoreserver/templates/scoreserver/index.html
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Hello SENSHU-CTF</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="{% static 'js/stream.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/cathode-ray_tube.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<input id="switch" type="checkbox" checked=""/>
<label for="switch" class="switch-label">Power </label>
<div class="container">
  <div class="screen">
    <div id="right" >
      <div id="stream_text" ></div>
    </div>
    <div id="main" >
    <h3>Hello SENSHU-CTF</h3>
    {% if user.is_authenticated %}
        <p>Hello! {{ user.get_username }}</p>
    {% endif %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url 'scoreserver:questions' %}"><img src="{% static 'images/Questions.png' %}"></a>
    <a href="{% url 'scoreserver:login' %}"><img src="{% static 'images/Login.png' %}"></a>
    <a href="{% url 'scoreserver:logout' %}"><img src="{% static 'images/Logout.png' %}"></a>
    <a href="{% url 'scoreserver:register' %}"><img src="{% static 'images/Register.png' %}"></a>
    </div>
  </div>
  <div class="overlay">Video1</div>
</div>
</body>

src/senshu/scoreserver/templates/scoreserver/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="jp">
<head>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% include "scoreserver/head.html" %}
</head>
<body>
  <div class="wrapper">
    {% if not user.is_authenticated %}
    <form class="form-signin" method="post" action="{% url 'scoreserver:login' %}">
      {% if login_failed %}
        <strong style="color:red;">Your Username or Password didn't match!! Please try again.</strong>
      {% endif %}
      {% if is_inactive %}
        <strong style="color:red;">Your user account is inactive.</strong>
      {% endif %}
      <h2 class="form-signin-heading">Please login</h2>
      <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
      <label class="checkbox">
        <input type="checkbox" value="true" id="rememberMe" name="rememberMe"> Remember me
      </label>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      {% csrf_token %}
    </form>
    {% else %}
    <strong style="color:red;">You had already logged in as {{ user }}!!</strong>
    <script>
      setTimeout(function(){location.href="{% url 'scoreserver:index' %}";}, 1000);
    </script>
    {% endif %}
  </div>
</body>

src/senshu/scoreserver/templates/scoreserver/logout.html
<!DOCTYPE html>
<html>
    <head>
        <title>ログアウト</title>
    </head>
    <body onload="setTimeout(function(){location.href='{% url 'scoreserver:index' %}';}, 1000);">
    <img src="http://stat.ameba.jp/user_images/20141018/00/m026/11/d7/j/t02200330_0800120013101213562.jpg" width="500" height="500"/>
    <h1>ばいば〜いwwwwwwwwwww</h1>
    {% if logout %}
        <h3 class="page-header">ログアウトしました。</h3>
    {% else %}
        <h3 class="page-header">ログアウトできませんでした。</h3>
    {% endif %}
    </body>
</html>

src/senshu/scoreserver/templates/scoreserver/particlejs.html
{% load staticfiles %}
<head>
  <script src="{% static 'js/particles.min.js' %}"></script>
  <script src="{% static 'js/particle_setting.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/particle.css' %}">
</head>

src/senshu/scoreserver/templates/scoreserver/question.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% include "scoreserver/bootstrap.html" %}
    {% include "scoreserver/head.html" %}
    {% include "scoreserver/sidebar.html" %}
    {% include "scoreserver/bootcard.html" %}
    <meta charset="utf-8"/>
    <title>{{ title }}</title>
</head>
<body>
  <div class="main">
    <div id="question-main">
      {% for question ,point in zipped_questions_points %}
      <div class="question_panel col-xs-6 col-sm-4" >
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <h3 class="panel-title pull-left" style="width:100%">{{ question.title }}</br></h3>
            <span class="label label-info pull-left">{{question.category}}</span>
            {% if not question.id in solved_questions %}
            <a class="btn pull-right" href="{% url 'scoreserver:question_detail' question.id %}">
              <i style="font-size:30px;z-index:0;" class="material-icons">pageview</i>
            </a>
            {% else %}
            <a class="btn pull-right" style="color:green" onclick="alert('You had already done this problem!')">
              <i style="font-size:2em" class="material-icons">done</i>
            </a>
            {% endif %}
          </div>
          <div class="list-group">
            <div class="list-group-item">
              <h4 class="list-group-item-heading">Solved</h4>
              <p class="list-group-item-text">{{ question.solved }}</p>
            </div>
            <div class="list-group-item">
              <h4 class="list-group-item-heading">Point</h4>
              <p class="list-group-item-text">{{ point }}</p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
    </div>
  </div>
</body>
</html>

src/senshu/scoreserver/templates/scoreserver/questions.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="jp">
<head>
  {% include "scoreserver/head.html" %}
  {% include "scoreserver/bootstrap.html" %}
  {% include "scoreserver/sidebar.html" %}
  <meta charset="utf-8"/>
  <title>{{ title }}</title>
</head>
<body>
  <div class="main">
    <div>&nbsp</br></div>
    {% for question ,point in zipped_questions_points %}
    {% if question.id in solved_questions %}
    {% endif %}
      <div class="question_panel col-xs-6 col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <h3 class="panel-title pull-left" style="width:100%">{{ question.title }}</h3>
            <span class="label label-info pull-left">{{question.category}}</span>
            {% if not question.id in solved_questions %}
            <a class="btn pull-right" href="{% url 'scoreserver:question_detail' question.id %}">
              <i style="font-size:2em" class="material-icons">pageview</i>
            </a>
            {% else %}
            <a class="btn pull-right" style="color:green" onclick="alert('You had already done this problem!')">
              <i style="font-size:2em" class="material-icons">done</i>
            </a>
            {% endif %}
          </div>
          <div class="list-group">
          <div class="list-group-item">
            <h4 class="list-group-item-heading">Solved</h4>
            <p class="list-group-item-text">{{ question.solved }}</p>
          </div>
          <div class="list-group-item">
            <h4 class="list-group-item-heading">Point</h4>
            <p class="list-group-item-text">{{ point }}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</body>
</html>

src/senshu/scoreserver/templates/scoreserver/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="jp">
<head>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% include "scoreserver/head.html" %}
</head>
<body>
  <div class="wrapper">
    <form class="form-signin" method="post" action="">
      <h2 class="form-signin-heading">Register</h2>
      {% for message in messages %}
        <strong style="color:red;">{{ message }}</strong>
      {% endfor %}
      <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
      {% csrf_token %}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
    </form>
  </div>
</body>

src/senshu/scoreserver/templates/scoreserver/sidebar.html
{% load staticfiles %}
<head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="{% static 'js/sidebar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
</head>
<div id="sidebar">
  <nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" id="side-scoreboard" href="{% url 'scoreserver:scoreboard' %}">ScoreBoard <br></a>
	    <a class="navbar-brand" href="{% url 'scoreserver:scoreboard' %}"> {{ login_user_rank }} / {{ all_user_num }} <i class="fa fa-line-chart"></i></a>
        <small class="navbar-brand"> {{ user.points }}pt </small>
      </div>
      <ul class="nav navbar-nav">
	<li>
          <a id="side-questions" href="{% url 'scoreserver:questions' %}">Questions</a>
        </li>
    <li>
        <li>
          <a id="side-web" href="{% url 'scoreserver:web' %}">Web
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-newspaper-o"></span>
          </a>
        </li>
	    <li >
          <a id="side-network" href="{% url 'scoreserver:network' %}">Network
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-wifi"></span>
          </a>
        </li>
        <li >
          <a id="side-crypt" href="{% url 'scoreserver:crypt' %}">Crypt
            <span style="font-size:24px;" class="pull-right hidden-xs showopacity fa fa-lock"></span>
          </a>
        </li>
	<li>
          <a id="side-forensics" href="{% url 'scoreserver:forensics' %}">Forensics
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-export"></span>
          </a>
        </li>
	<li>
          <a id="side-reversing" href="{% url 'scoreserver:reversing' %}">Binary
            <span class="pull-right hidden-xs showopacity"><i style="font-size:18px" class="material-icons">memory</i></span>
          </a>
        </li>
	<li>
          <a id="side-misc" href="{% url 'scoreserver:misc' %}">Misc
            <span class="pull-right hidden-xs showopacity"><i style="font-size:18px" class="material-icons">folder</i></span>
          </a>
        </li>
    <li>
          <a href="{% url 'scoreserver:logout' %}">Logout
            <span class="pull-right hidden-xs showopacity"><i style="font-size:18px" class="material-icons">directions_walk</i></span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>